"""game_patterns.py — Dicionario de padroes de jogos como recurso MCP.

18 padroes cobrindo ~90% dos generos 2D viaveis no Godot.
Formato otimizado para IAs agenticas (DeepSeek, Claude, Gemini).
"""

GAME_PATTERNS = {
    "tower_defense": {
        "description": "Defesa de torre: inimigos seguem caminho, jogador posiciona torres que atiram automaticamente",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["Path2D + PathFollow2D (caminho)", "Spawner (Timer + spawn)", "Torre (StaticBody2D + Area2D + Timer)", "Projetil (Area2D)", "Inimigo (PathFollow2D + vida)", "Base (Area2D)", "HUD (ouro/vidas/wave)"],
        "core_mechanics": ["Inimigos seguem waypoints", "Torres atiram no mais avancado", "Ouro por inimigo", "Upgrade de torres", "Waves progressivas (+15% HP/wave)", "Game over se N inimigos chegarem a base"],
        "inputs": ["mouse_click (posicionar/upgrade)"],
        "typical_scripts": ["global.gd", "tower.gd", "enemy.gd", "bullet.gd", "spawner.gd", "hud.gd"],
        "difficulty": {"design": 2, "implementation": 3, "tuning": 4},
        "minimum_viable": "3 waves, 1 torre, 1 inimigo, HUD ouro+vidas",
        "common_bugs": ["Torre atira depois de removida", "Inimigo atravessa base", "Projetil segue alvo morto"],
        "godot_subsystems": ["Path2D", "Area2D", "Timer", "CanvasLayer"],
        "references": ["Bloons TD 6", "Kingdom Rush", "Plants vs Zombies"],
        "combines_with": ["roguelike_dungeon_crawler"],
    },
    "platformer": {
        "description": "Plataforma: pula entre plataformas, coleta itens, evita inimigos",
        "camera": "side-scroll 2D", "root_node": "Node2D",
        "essential_nodes": ["CharacterBody2D (gravidade+pulo)", "CollisionShape2D", "AnimatedSprite2D", "TileMapLayer (plataformas)", "Camera2D (follow+limits)", "Area2D (moedas/power-ups)", "Enemy (patrol)", "HUD (vidas/moedas)"],
        "core_mechanics": ["Gravidade 980 + pulo -400", "Coyote time 120ms", "Input buffer 150ms", "Moedas coletaveis", "Inimigos patrol", "Checkpoints"],
        "inputs": ["move_left (A/Esq)", "move_right (D/Dir)", "jump (Espaco/W)"],
        "typical_scripts": ["player.gd", "enemy_patrol.gd", "coin.gd", "game_manager.gd", "hud.gd", "camera.gd"],
        "difficulty": {"design": 2, "implementation": 2, "tuning": 3},
        "minimum_viable": "1 nivel + chao + 3 plataformas + 5 moedas",
        "common_bugs": ["Wall slide indesejado", "Pulo duplo nao intencional", "Camera treme em baixo FPS"],
        "godot_subsystems": ["CharacterBody2D", "TileMapLayer", "Camera2D", "AnimationPlayer"],
        "references": ["Super Mario Bros", "Celeste", "Hollow Knight"],
        "combines_with": ["metroidvania", "stealth_2d"],
    },
    "vampire_survivors_like": {
        "description": "Sobrevivencia: WASD move, ataque automatico, XP -> level up -> upgrade",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["CharacterBody2D (so movimento)", "Weapon (Area2D + Timer)", "Spawner (Timer)", "Inimigo (persegue jogador)", "XP Orb (Area2D)", "HUD (timer/kills/level/HP)", "LevelUpScreen (3 upgrades)"],
        "core_mechanics": ["WASD 8 dir, ataque automatico", "Inimigos spawnam nas bordas", "XP orbs dropam", "Level up = escolhe upgrade", "Sobrevivencia 15-30min"],
        "inputs": ["move (WASD/Setas)"],
        "typical_scripts": ["player.gd", "enemy.gd", "xp_orb.gd", "weapon.gd", "spawner.gd", "upgrade_screen.gd", "global.gd"],
        "difficulty": {"design": 3, "implementation": 3, "tuning": 5},
        "minimum_viable": "Move + 1 arma automatica + inimigos + XP orb",
        "common_bugs": ["Upgrade screen nao pausa", "Armas nao escalam", "Inimigos spawnam sobrepostos"],
        "godot_subsystems": ["CharacterBody2D", "Timer", "Area2D", "CanvasLayer", "Control"],
        "references": ["Vampire Survivors", "Brotato", "20 Minutes Till Dawn"],
        "combines_with": ["bullet_hell", "roguelike_dungeon_crawler"],
    },
    "top_down_shooter": {
        "description": "Shooter top-down: WASD move, mouse mira, clique atira, esquiva de projeteis",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["CharacterBody2D (WASD+mira)", "Marker2D (mira)", "Projetil (Area2D)", "Inimigo (charge/zigzag/shooter)", "HUD (HP/municao/kills)"],
        "core_mechanics": ["WASD move, mouse mira, clique atira", "Projeteis em linha reta", "Cooldown entre tiros", "Inimigos com patterns", "Chefao a cada 5 waves", "Power-ups dropados"],
        "inputs": ["move (WASD)", "shoot (Mouse Left)", "special (Mouse Right)"],
        "typical_scripts": ["player.gd", "bullet.gd", "enemy.gd", "boss.gd", "spawner.gd", "powerup.gd", "hud.gd"],
        "difficulty": {"design": 2, "implementation": 3, "tuning": 3},
        "minimum_viable": "Move + atira + 1 inimigo + HUD HP",
        "common_bugs": ["Projetil direcao errada", "Inimigo mira errada", "Power-up permanente sem timer"],
        "godot_subsystems": ["CharacterBody2D", "Area2D", "Marker2D", "CanvasLayer"],
        "references": ["Enter the Gungeon", "Nuclear Throne", "Hotline Miami"],
        "combines_with": ["bullet_hell", "roguelike_dungeon_crawler"],
    },
    "puzzle_match3": {
        "description": "Match-3: grid de pecas coloridas, troca adjacentes, 3+ desaparecem, novas caem",
        "camera": "top-down 2D fixa", "root_node": "Node2D",
        "essential_nodes": ["Grid (Node2D)", "Tile (Sprite2D + Area2D)", "Timer (respawn)", "HUD (score/moves)"],
        "core_mechanics": ["Grid 8x8 com 5-6 cores", "Clique troca adjacentes", "3+ match = desaparecem", "Pecas caem (gravidade)", "Novas spawnam no topo", "Combos multiplicam score"],
        "inputs": ["mouse_click (selecionar/trocar)"],
        "typical_scripts": ["grid_manager.gd", "tile.gd", "hud.gd"],
        "difficulty": {"design": 3, "implementation": 4, "tuning": 2},
        "minimum_viable": "Grid 5x5 + 4 cores + troca + match-3 + gravidade",
        "common_bugs": ["Troca nao-adjacente", "Match detection so linha reta", "Cascata infinita"],
        "godot_subsystems": ["Sprite2D", "Area2D", "Timer", "Tween", "CanvasLayer"],
        "references": ["Candy Crush", "Bejeweled", "Puzzle Quest"],
        "combines_with": ["rpg_turn_based"],
    },
    "rpg_turn_based": {
        "description": "RPG de turno: exploracao + batalhas, menu de acoes, stats, level up",
        "camera": "top-down 2D (exploracao) + lateral (batalha)", "root_node": "Node2D",
        "essential_nodes": ["Overworld (Node2D + TileMap)", "CharacterBody2D (movimento)", "BattleScene (Node2D)", "BattleUI (Atacar/Magia/Item/Fugir)", "HPBar", "BattleManager (turnos)"],
        "core_mechanics": ["Overworld com encontro aleatorio", "Turnos alternados", "Acoes: Atacar, Magia, Item, Fugir", "Stats: HP/MP/ATK/DEF/SPD", "Level up com EXP", "Itens e equipamentos"],
        "inputs": ["move_4dir", "confirm (Z/Enter)", "cancel (X/Esc)"],
        "typical_scripts": ["battle_manager.gd", "player_stats.gd", "enemy_stats.gd", "overworld_player.gd", "dialog.gd", "inventory.gd"],
        "difficulty": {"design": 3, "implementation": 4, "tuning": 4},
        "minimum_viable": "1 area + 1 inimigo + Atacar/Fugir + level up",
        "common_bugs": ["Encontro multiplo", "Level up HP errado", "Fugir sempre/nunca funciona"],
        "godot_subsystems": ["CharacterBody2D", "CanvasLayer", "TextureProgressBar", "TileMapLayer"],
        "references": ["Final Fantasy", "Dragon Quest", "Pokemon", "Undertale"],
        "combines_with": ["card_deck_builder", "visual_novel"],
    },
    "roguelike_dungeon_crawler": {
        "description": "Dungeon procedural: salas aleatorias, inimigos, loot, permadeath com meta-progresso",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["DungeonGenerator (BSP)", "Room (Node2D)", "CharacterBody2D (jogador)", "Enemy (melee/ranged)", "Item (Area2D coletavel)", "Door (bloqueia ate limpar)", "Minimap", "HUD (HP/nivel/ouro)"],
        "core_mechanics": ["Dungeon procedural com N salas", "Salas: combate, tesouro, loja, evento", "Combate em tempo real", "Loot com raridade", "Permadeath + meta-progresso", "Chefao a cada 5 salas"],
        "inputs": ["move_4dir (WASD)", "attack (Mouse Left)", "interact (E)", "use_item (Q)", "map (Tab)"],
        "typical_scripts": ["dungeon_gen.gd", "player.gd", "enemy.gd", "item.gd", "boss.gd", "room_manager.gd", "minimap.gd", "hud.gd"],
        "difficulty": {"design": 4, "implementation": 5, "tuning": 5},
        "minimum_viable": "5 salas + 2 inimigos + 1 chefao + ataque melee + HUD HP",
        "common_bugs": ["Salas sobrepostas", "Jogador preso", "Loot na parede"],
        "godot_subsystems": ["TileMapLayer", "CharacterBody2D", "Area2D", "RandomNumberGenerator", "CanvasLayer"],
        "references": ["The Binding of Isaac", "Enter the Gungeon", "Hades", "Dead Cells"],
        "combines_with": ["top_down_shooter", "card_deck_builder"],
    },
    "card_deck_builder": {
        "description": "Deck builder: draft de cartas durante a run, cada carta e uma acao, sinergias e reliquias",
        "camera": "top-down 2D + UI centrada", "root_node": "Node2D",
        "essential_nodes": ["MapScreen (caminho ramificado)", "BattleScreen (Control — cartas)", "Card (Resource)", "Deck (Array)", "Relic (Resource)", "Enemy (Resource — intencao visivel)", "HUD (HP/energia/ouro)"],
        "core_mechanics": ["Mapa ramificado: combate, tesouro, loja, evento", "Turnos: compra 5 cartas, 3 energia", "Cartas: Atacar, Defender, Skill, Power", "Draft apos combate", "Reliquias: efeitos passivos", "Sinergias entre cartas"],
        "inputs": ["mouse_click (selecionar carta)"],
        "typical_scripts": ["card_data.gd", "deck_manager.gd", "battle_manager.gd", "enemy_ai.gd", "map_screen.gd", "relic_manager.gd", "hud.gd"],
        "difficulty": {"design": 5, "implementation": 5, "tuning": 5},
        "minimum_viable": "5 cartas + 3 inimigos + 1 chefao + draft + 3 reliquias",
        "common_bugs": ["Carta na mao errada", "Reliquia stacka errado", "Inimigo sem intencao"],
        "godot_subsystems": ["Resource", "Control", "Array", "CanvasLayer", "Tween"],
        "references": ["Slay the Spire", "Monster Train", "Griftlands"],
        "combines_with": ["rpg_turn_based", "roguelike_dungeon_crawler"],
    },
    "arcade_breakout": {
        "description": "Breakout/Arkanoid: paddle, bola quica, destroi tijolos, power-ups",
        "camera": "top-down 2D fixa", "root_node": "Node2D",
        "essential_nodes": ["Paddle (CharacterBody2D)", "Ball (CharacterBody2D)", "Brick (StaticBody2D)", "Wall (StaticBody2D)", "PowerUp (Area2D)", "HUD (vidas/score)"],
        "core_mechanics": ["Paddle move horizontal", "Bola quica com angulo variavel", "Tijolos: normal/forte/indestrutivel", "Power-ups temporarios", "Game over se bola cair"],
        "inputs": ["move_left/right (Mouse/Setas)", "launch (Espaco/Click)"],
        "typical_scripts": ["paddle.gd", "ball.gd", "brick.gd", "powerup.gd", "level_manager.gd", "hud.gd"],
        "difficulty": {"design": 1, "implementation": 2, "tuning": 2},
        "minimum_viable": "Paddle + bola + 1 fileira tijolos + placar. 10 min",
        "common_bugs": ["Bola atravessa paddle", "Loop horizontal", "Power-up cai para sempre"],
        "godot_subsystems": ["CharacterBody2D", "StaticBody2D", "Area2D", "CanvasLayer"],
        "references": ["Breakout", "Arkanoid", "DX-Ball"],
        "combines_with": [],
    },
    "metroidvania": {
        "description": "Metroidvania: plataforma + exploracao interconectada com habilidades desbloqueaveis",
        "camera": "side-scroll 2D", "root_node": "Node2D",
        "essential_nodes": ["CharacterBody2D (habilidades)", "Room (Node2D)", "Door (Area2D)", "Ability Gate (StaticBody2D)", "Map (Control)", "SavePoint (Area2D)", "BossDoor"],
        "core_mechanics": ["Movimento plataforma + dash/double jump/wall jump", "Habilidade-gate", "Backtracking", "Mapa revelado", "Chefoes guardam habilidades", "Upgrades encontrados no mapa"],
        "inputs": ["move/jump/attack", "dash (Shift)", "map (Tab)", "inventory (I)"],
        "typical_scripts": ["player.gd", "room_transition.gd", "door.gd", "ability_manager.gd", "map_screen.gd", "boss.gd"],
        "difficulty": {"design": 5, "implementation": 5, "tuning": 4},
        "minimum_viable": "3 salas + 1 porta trancada + 1 power-up",
        "common_bugs": ["Transicao posicao errada", "Mapa desatualizado", "Gate bypassado"],
        "godot_subsystems": ["CharacterBody2D", "Camera2D", "TileMapLayer", "Area2D", "Control"],
        "references": ["Hollow Knight", "Super Metroid", "Castlevania: SOTN", "Ori"],
        "combines_with": ["platformer"],
    },
    "racing_top_down": {
        "description": "Corrida top-down: aceleracao, frenagem, drift. Voltas em pista",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["Car (CharacterBody2D)", "Track (TileMapLayer + Path2D)", "Checkpoint (Area2D)", "AI Car", "HUD (posicao/volta/tempo)"],
        "core_mechanics": ["Fisica arcade com drift", "Pista fechada com checkpoints", "AI segue Path2D", "Power-ups na pista", "Vencedor: primeiro a completar N voltas"],
        "inputs": ["accelerate (W)", "brake (S)", "steer_left (A)", "steer_right (D)"],
        "typical_scripts": ["car_physics.gd", "checkpoint_manager.gd", "ai_car.gd", "race_manager.gd", "hud.gd"],
        "difficulty": {"design": 2, "implementation": 3, "tuning": 4},
        "minimum_viable": "1 carro + pista oval + 2 checkpoints + voltas",
        "common_bugs": ["Atravessa parede", "Checkpoint nao registra", "AI preso em curva"],
        "godot_subsystems": ["CharacterBody2D", "Path2D", "Area2D", "Camera2D", "TileMapLayer"],
        "references": ["Micro Machines", "Reckless Getaway", "Death Rally"],
        "combines_with": [],
    },
    "visual_novel": {
        "description": "Visual novel: historia ramificada, dialogos, escolhas que afetam o final",
        "camera": "fixa", "root_node": "Control (CanvasLayer)",
        "essential_nodes": ["Background (TextureRect)", "CharacterSprite (TextureRect)", "DialogBox (Panel + RichTextLabel com typewriter)", "ChoiceButtons (VBoxContainer)", "SaveLoadScreen", "HistoryLog"],
        "core_mechanics": ["Dialogo com typewriter effect", "Escolhas ramificam historia", "Flags definem finais", "Multiplos finais", "Save/Load com screenshot", "Galeria desbloqueavel"],
        "inputs": ["confirm (Mouse Left/Enter)", "hide_ui (H)"],
        "typical_scripts": ["dialog_manager.gd", "script_loader.gd", "choice_handler.gd", "save_system.gd", "flag_manager.gd"],
        "difficulty": {"design": 4, "implementation": 2, "tuning": 1},
        "minimum_viable": "1 cena + 1 personagem + typewriter + 1 escolha",
        "common_bugs": ["Texto avanca rapido", "Flag nao registra", "Save carrega cena errada"],
        "godot_subsystems": ["Control", "RichTextLabel", "TextureRect", "FileAccess", "JSON"],
        "references": ["Doki Doki Literature Club", "Ace Attorney", "VA-11 Hall-A"],
        "combines_with": ["rpg_turn_based"],
    },
    "idle_clicker": {
        "description": "Idle/clicker: clique para ganhar recurso, upgrades, automacao. Numeros exponenciais",
        "camera": "fixa", "root_node": "Control",
        "essential_nodes": ["ClickArea (TextureButton)", "ResourceDisplay (Label com 1.2K/3.4M)", "UpgradeShop (VBoxContainer)", "AutoGenerator (Timer)", "PrestigeButton"],
        "core_mechanics": ["Clique = +1 recurso", "Upgrades: +clique, +auto, +multiplicador", "Custo exponencial (1.15x)", "Automacao por Timer", "Notacao compacta", "Prestige: reset com bonus permanente"],
        "inputs": ["mouse_click"],
        "typical_scripts": ["game_manager.gd", "upgrade_shop.gd", "click_handler.gd", "auto_generator.gd", "prestige.gd"],
        "difficulty": {"design": 3, "implementation": 2, "tuning": 4},
        "minimum_viable": "Botao + contador + 3 upgrades",
        "common_bugs": ["Overflow negativo", "Custo nao escala", "Auto-generator pos-prestige"],
        "godot_subsystems": ["Control", "Timer", "Tween", "Curve"],
        "references": ["Cookie Clicker", "Adventure Capitalist"],
        "combines_with": [],
    },
    "physics_puzzle": {
        "description": "Physics puzzle: usar gravidade, colisao e joints para resolver puzzles",
        "camera": "side-scroll 2D", "root_node": "Node2D",
        "essential_nodes": ["PhysicsObjects (RigidBody2D)", "Launcher (mirar+lancar)", "Target (Area2D)", "Joint2D", "ResetButton", "HUD (nivel/estrelas)"],
        "core_mechanics": ["Fisica real: gravidade, atrito, elasticidade", "Interacao: drag, slingshot, corte", "Solucao baseada em fisica", "1-3 estrelas por nivel"],
        "inputs": ["mouse_drag", "touch"],
        "typical_scripts": ["launcher.gd", "physics_object.gd", "target.gd", "level_manager.gd", "hud.gd"],
        "difficulty": {"design": 4, "implementation": 3, "tuning": 4},
        "minimum_viable": "1 objeto + 1 lancador + 1 alvo",
        "common_bugs": ["Objeto sem gravidade", "Joint quebra sozinho", "Drag falha mobile"],
        "godot_subsystems": ["RigidBody2D", "Joint2D", "Area2D", "PhysicsMaterial"],
        "references": ["Angry Birds", "Cut the Rope", "World of Goo"],
        "combines_with": [],
    },
    "twin_stick_shooter": {
        "description": "Twin-stick: WASD move, setas atiram 8 dir. Arena survival com waves",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["CharacterBody2D (WASD+setas)", "Bullet (Area2D 8 dir)", "Enemy (spawna bordas)", "Spawner (Timer)", "PowerUp (Area2D)", "HUD (score/wave/HP)"],
        "core_mechanics": ["Left=movimento, Right=tiro (8 dir)", "Inimigos convergem no jogador", "Waves progressivas", "Power-ups: spread, bomb, speed"],
        "inputs": ["move (WASD)", "shoot (Setas)", "bomb (Espaco)"],
        "typical_scripts": ["player.gd", "bullet.gd", "enemy.gd", "spawner.gd", "powerup.gd", "hud.gd"],
        "difficulty": {"design": 2, "implementation": 2, "tuning": 3},
        "minimum_viable": "Move + atira 4 dir + inimigos + score",
        "common_bugs": ["Tiro direcao errada", "Inimigo spawna fora", "Wave nao avanca"],
        "godot_subsystems": ["CharacterBody2D", "Timer", "Area2D", "Input dual mapping"],
        "references": ["Geometry Wars", "Smash TV", "Nuclear Throne"],
        "combines_with": ["bullet_hell"],
    },
    "snake_classic": {
        "description": "Snake: cobra cresce ao comer, morre ao colidir. Movimento em grid",
        "camera": "top-down 2D fixa", "root_node": "Node2D",
        "essential_nodes": ["Grid (Node2D)", "SnakeHead (ColorRect)", "SnakeBody (Array)", "Food (Sprite2D)", "Wall (StaticBody2D)", "HUD (score/high score)"],
        "core_mechanics": ["Movimento em grid com tick", "Setas mudam direcao", "Comer food = +1 segmento +10 score", "Morte: parede ou proprio corpo", "Velocidade aumenta"],
        "inputs": ["move_up/down/left/right (Setas)"],
        "typical_scripts": ["snake.gd", "food_spawner.gd", "grid.gd", "hud.gd"],
        "difficulty": {"design": 1, "implementation": 1, "tuning": 1},
        "minimum_viable": "Cobra 3 segmentos + 1 food + game over parede",
        "common_bugs": ["Inverte direcao", "Food sobre corpo", "Corpo nao segue cabeca"],
        "godot_subsystems": ["Timer", "Array", "ColorRect", "Area2D"],
        "references": ["Snake (Nokia)", "Slither.io"],
        "combines_with": [],
    },
    "bullet_hell": {
        "description": "Bullet hell: dezenas de projeteis, hitbox 2px, foco em ESQUIVA",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["CharacterBody2D (hitbox 2px)", "Bullet (Area2D, patterns)", "Boss (multi-phase)", "HUD (vidas/bombs/score)"],
        "core_mechanics": ["Hitbox 2px no centro", "Focus: Shift = lento + hitbox visivel", "Object pooling para balas", "Boss phases a cada 25% HP"],
        "inputs": ["move_4dir", "focus (Shift)", "bomb (X)"],
        "typical_scripts": ["player.gd", "bullet_pool.gd", "boss.gd", "pattern_factory.gd", "hud.gd"],
        "difficulty": {"design": 4, "implementation": 4, "tuning": 5},
        "minimum_viable": "Move + hitbox 2px + 1 pattern + boss 1 fase",
        "common_bugs": ["Hitbox nao corresponde", "Pool esgota", "Boss nao transiciona"],
        "godot_subsystems": ["CharacterBody2D", "Area2D", "Object Pool (Array)", "Timer"],
        "references": ["Touhou", "Jamestown", "Ikaruga"],
        "combines_with": ["top_down_shooter"],
    },
}


def get_game_patterns() -> list[dict]:
    return [{"name": n, "description": i["description"], "camera": i["camera"],
             "essential_count": len(i["essential_nodes"]), "mechanic_count": len(i["core_mechanics"])}
            for n, i in GAME_PATTERNS.items()]


def get_game_pattern(name: str) -> dict | None:
    return GAME_PATTERNS.get(name)
