"""game_patterns.py — Dicionario de padroes de jogos como recurso MCP.

32 padroes cobrindo ~100% dos generos 2D viaveis no Godot.
Formato otimizado para IAs agenticas (DeepSeek, Claude, Gemini).
"""

GAME_PATTERNS = {
    "tower_defense": {
        "description": "Defesa de torre: inimigos seguem caminho, jogador posiciona torres que atiram automaticamente",
        "quickstart_phrase_pt": "jogo de defesa de torre, inimigos seguem um caminho e voce posiciona torres",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["Path2D + PathFollow2D (caminho)", "Spawner (Timer + spawn)", "Torre (StaticBody2D + Area2D + Timer)", "Projetil (Area2D)", "Inimigo (PathFollow2D + vida)", "Base (Area2D)", "HUD (ouro/vidas/wave)"],
        "core_mechanics": ["Inimigos seguem waypoints", "Torres atiram no mais avancado", "Ouro por inimigo", "Upgrade de torres", "Waves progressivas (+15% HP/wave)", "Game over se N inimigos chegarem a base"],
        "inputs": ["mouse_click (posicionar/upgrade)"],
        "typical_scripts": ["global.gd", "tower.gd", "enemy.gd", "bullet.gd", "spawner.gd", "hud.gd"],
        "difficulty": {"design": 2, "implementation": 3, "tuning": 4},
        "minimum_viable": "3 waves, 1 torre, 1 inimigo, HUD ouro+vidas",
        "common_bugs": ["Torre atira depois de removida", "Inimigo atravessa base", "Projetil segue alvo morto"],
        "godot_subsystems": ["Path2D", "Area2D", "Timer", "CanvasLayer"],
        "references": ["Bloons TD 6", "Kingdom Rush", "Plants vs Zombies"],
        "combines_with": ["roguelike_dungeon_crawler"],
    },
    "platformer": {
        "description": "Plataforma: pula entre plataformas, coleta itens, evita inimigos",
        "quickstart_phrase_pt": "jogo de plataforma com pulo, coleta de moedas e inimigos no caminho",
        "camera": "side-scroll 2D", "root_node": "Node2D",
        "essential_nodes": ["CharacterBody2D (gravidade+pulo)", "CollisionShape2D", "AnimatedSprite2D", "TileMapLayer (plataformas)", "Camera2D (follow+limits)", "Area2D (moedas/power-ups)", "Enemy (patrol)", "HUD (vidas/moedas)"],
        "core_mechanics": ["Gravidade 980 + pulo -400", "Coyote time 120ms", "Input buffer 150ms", "Moedas coletaveis", "Inimigos patrol", "Checkpoints"],
        "inputs": ["move_left (A/Esq)", "move_right (D/Dir)", "jump (Espaco/W)"],
        "typical_scripts": ["player.gd", "enemy_patrol.gd", "coin.gd", "game_manager.gd", "hud.gd", "camera.gd"],
        "difficulty": {"design": 2, "implementation": 2, "tuning": 3},
        "minimum_viable": "1 nivel + chao + 3 plataformas + 5 moedas",
        "common_bugs": ["Wall slide indesejado", "Pulo duplo nao intencional", "Camera treme em baixo FPS"],
        "godot_subsystems": ["CharacterBody2D", "TileMapLayer", "Camera2D", "AnimationPlayer"],
        "references": ["Super Mario Bros", "Celeste", "Hollow Knight"],
        "combines_with": ["metroidvania", "stealth_2d"],
    },
    "vampire_survivors_like": {
        "description": "Sobrevivencia: WASD move, ataque automatico, XP -> level up -> upgrade",
        "quickstart_phrase_pt": "jogo de sobrevivencia com ataque automatico, waves de inimigos e evolucao por nivel",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["CharacterBody2D (so movimento)", "Weapon (Area2D + Timer)", "Spawner (Timer)", "Inimigo (persegue jogador)", "XP Orb (Area2D)", "HUD (timer/kills/level/HP)", "LevelUpScreen (3 upgrades)"],
        "core_mechanics": ["WASD 8 dir, ataque automatico", "Inimigos spawnam nas bordas", "XP orbs dropam", "Level up = escolhe upgrade", "Sobrevivencia 15-30min"],
        "inputs": ["move (WASD/Setas)"],
        "typical_scripts": ["player.gd", "enemy.gd", "xp_orb.gd", "weapon.gd", "spawner.gd", "upgrade_screen.gd", "global.gd"],
        "difficulty": {"design": 3, "implementation": 3, "tuning": 5},
        "minimum_viable": "Move + 1 arma automatica + inimigos + XP orb",
        "common_bugs": ["Upgrade screen nao pausa", "Armas nao escalam", "Inimigos spawnam sobrepostos"],
        "godot_subsystems": ["CharacterBody2D", "Timer", "Area2D", "CanvasLayer", "Control"],
        "references": ["Vampire Survivors", "Brotato", "20 Minutes Till Dawn"],
        "combines_with": ["bullet_hell", "roguelike_dungeon_crawler"],
    },
    "top_down_shooter": {
        "description": "Shooter top-down: WASD move, mouse mira, clique atira, esquiva de projeteis",
        "quickstart_phrase_pt": "jogo de nave que atira em asteroides, desvie dos inimigos e colete power-ups",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["CharacterBody2D (WASD+mira)", "Marker2D (mira)", "Projetil (Area2D)", "Inimigo (charge/zigzag/shooter)", "HUD (HP/municao/kills)"],
        "core_mechanics": ["WASD move, mouse mira, clique atira", "Projeteis em linha reta", "Cooldown entre tiros", "Inimigos com patterns", "Chefao a cada 5 waves", "Power-ups dropados"],
        "inputs": ["move (WASD)", "shoot (Mouse Left)", "special (Mouse Right)"],
        "typical_scripts": ["player.gd", "bullet.gd", "enemy.gd", "boss.gd", "spawner.gd", "powerup.gd", "hud.gd"],
        "difficulty": {"design": 2, "implementation": 3, "tuning": 3},
        "minimum_viable": "Move + atira + 1 inimigo + HUD HP",
        "common_bugs": ["Projetil direcao errada", "Inimigo mira errada", "Power-up permanente sem timer"],
        "godot_subsystems": ["CharacterBody2D", "Area2D", "Marker2D", "CanvasLayer"],
        "references": ["Enter the Gungeon", "Nuclear Throne", "Hotline Miami"],
        "combines_with": ["bullet_hell", "roguelike_dungeon_crawler"],
    },
    "puzzle_match3": {
        "description": "Match-3: grid de pecas coloridas, troca adjacentes, 3+ desaparecem, novas caem",
        "quickstart_phrase_pt": "jogo de combinar 3 pecas coloridas no grid, troque posicoes para fazer pontos",
        "camera": "top-down 2D fixa", "root_node": "Node2D",
        "essential_nodes": ["Grid (Node2D)", "Tile (Sprite2D + Area2D)", "Timer (respawn)", "HUD (score/moves)"],
        "core_mechanics": ["Grid 8x8 com 5-6 cores", "Clique troca adjacentes", "3+ match = desaparecem", "Pecas caem (gravidade)", "Novas spawnam no topo", "Combos multiplicam score"],
        "inputs": ["mouse_click (selecionar/trocar)"],
        "typical_scripts": ["grid_manager.gd", "tile.gd", "hud.gd"],
        "difficulty": {"design": 3, "implementation": 4, "tuning": 2},
        "minimum_viable": "Grid 5x5 + 4 cores + troca + match-3 + gravidade",
        "common_bugs": ["Troca nao-adjacente", "Match detection so linha reta", "Cascata infinita"],
        "godot_subsystems": ["Sprite2D", "Area2D", "Timer", "Tween", "CanvasLayer"],
        "references": ["Candy Crush", "Bejeweled", "Puzzle Quest"],
        "combines_with": ["rpg_turn_based"],
    },
    "rpg_turn_based": {
        "description": "RPG de turno: exploracao + batalhas, menu de acoes, stats, level up",
        "quickstart_phrase_pt": "jogo de RPG de turno, explore o mapa, encontre inimigos e lute em batalhas por turno",
        "camera": "top-down 2D (exploracao) + lateral (batalha)", "root_node": "Node2D",
        "essential_nodes": ["Overworld (Node2D + TileMap)", "CharacterBody2D (movimento)", "BattleScene (Node2D)", "BattleUI (Atacar/Magia/Item/Fugir)", "HPBar", "BattleManager (turnos)"],
        "core_mechanics": ["Overworld com encontro aleatorio", "Turnos alternados", "Acoes: Atacar, Magia, Item, Fugir", "Stats: HP/MP/ATK/DEF/SPD", "Level up com EXP", "Itens e equipamentos"],
        "inputs": ["move_4dir", "confirm (Z/Enter)", "cancel (X/Esc)"],
        "typical_scripts": ["battle_manager.gd", "player_stats.gd", "enemy_stats.gd", "overworld_player.gd", "dialog.gd", "inventory.gd"],
        "difficulty": {"design": 3, "implementation": 4, "tuning": 4},
        "minimum_viable": "1 area + 1 inimigo + Atacar/Fugir + level up",
        "common_bugs": ["Encontro multiplo", "Level up HP errado", "Fugir sempre/nunca funciona"],
        "godot_subsystems": ["CharacterBody2D", "CanvasLayer", "TextureProgressBar", "TileMapLayer"],
        "references": ["Final Fantasy", "Dragon Quest", "Pokemon", "Undertale"],
        "combines_with": ["card_deck_builder", "visual_novel"],
    },
    "roguelike_dungeon_crawler": {
        "description": "Dungeon procedural: salas aleatorias, inimigos, loot, permadeath com meta-progresso",
        "quickstart_phrase_pt": "jogo de dungeon procedural, explore salas aleatorias, colete loot e enfrente chefes",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["DungeonGenerator (BSP)", "Room (Node2D)", "CharacterBody2D (jogador)", "Enemy (melee/ranged)", "Item (Area2D coletavel)", "Door (bloqueia ate limpar)", "Minimap", "HUD (HP/nivel/ouro)"],
        "core_mechanics": ["Dungeon procedural com N salas", "Salas: combate, tesouro, loja, evento", "Combate em tempo real", "Loot com raridade", "Permadeath + meta-progresso", "Chefao a cada 5 salas"],
        "inputs": ["move_4dir (WASD)", "attack (Mouse Left)", "interact (E)", "use_item (Q)", "map (Tab)"],
        "typical_scripts": ["dungeon_gen.gd", "player.gd", "enemy.gd", "item.gd", "boss.gd", "room_manager.gd", "minimap.gd", "hud.gd"],
        "difficulty": {"design": 4, "implementation": 5, "tuning": 5},
        "minimum_viable": "5 salas + 2 inimigos + 1 chefao + ataque melee + HUD HP",
        "common_bugs": ["Salas sobrepostas", "Jogador preso", "Loot na parede"],
        "godot_subsystems": ["TileMapLayer", "CharacterBody2D", "Area2D", "RandomNumberGenerator", "CanvasLayer"],
        "references": ["The Binding of Isaac", "Enter the Gungeon", "Hades", "Dead Cells"],
        "combines_with": ["top_down_shooter", "card_deck_builder"],
    },
    "card_deck_builder": {
        "description": "Deck builder: draft de cartas durante a run, cada carta e uma acao, sinergias e reliquias",
        "quickstart_phrase_pt": "jogo de cartas estrategico, monte seu deck durante a partida e combine sinergias",
        "camera": "top-down 2D + UI centrada", "root_node": "Node2D",
        "essential_nodes": ["MapScreen (caminho ramificado)", "BattleScreen (Control — cartas)", "Card (Resource)", "Deck (Array)", "Relic (Resource)", "Enemy (Resource — intencao visivel)", "HUD (HP/energia/ouro)"],
        "core_mechanics": ["Mapa ramificado: combate, tesouro, loja, evento", "Turnos: compra 5 cartas, 3 energia", "Cartas: Atacar, Defender, Skill, Power", "Draft apos combate", "Reliquias: efeitos passivos", "Sinergias entre cartas"],
        "inputs": ["mouse_click (selecionar carta)"],
        "typical_scripts": ["card_data.gd", "deck_manager.gd", "battle_manager.gd", "enemy_ai.gd", "map_screen.gd", "relic_manager.gd", "hud.gd"],
        "difficulty": {"design": 5, "implementation": 5, "tuning": 5},
        "minimum_viable": "5 cartas + 3 inimigos + 1 chefao + draft + 3 reliquias",
        "common_bugs": ["Carta na mao errada", "Reliquia stacka errado", "Inimigo sem intencao"],
        "godot_subsystems": ["Resource", "Control", "Array", "CanvasLayer", "Tween"],
        "references": ["Slay the Spire", "Monster Train", "Griftlands"],
        "combines_with": ["rpg_turn_based", "roguelike_dungeon_crawler"],
    },
    "arcade_breakout": {
        "description": "Breakout/Arkanoid: paddle, bola quica, destroi tijolos, power-ups",
        "quickstart_phrase_pt": "jogo de quebrar tijolos com bola e paddle, colete power-ups e destrua todos os blocos",
        "camera": "top-down 2D fixa", "root_node": "Node2D",
        "essential_nodes": ["Paddle (CharacterBody2D)", "Ball (CharacterBody2D)", "Brick (StaticBody2D)", "Wall (StaticBody2D)", "PowerUp (Area2D)", "HUD (vidas/score)"],
        "core_mechanics": ["Paddle move horizontal", "Bola quica com angulo variavel", "Tijolos: normal/forte/indestrutivel", "Power-ups temporarios", "Game over se bola cair"],
        "inputs": ["move_left/right (Mouse/Setas)", "launch (Espaco/Click)"],
        "typical_scripts": ["paddle.gd", "ball.gd", "brick.gd", "powerup.gd", "level_manager.gd", "hud.gd"],
        "difficulty": {"design": 1, "implementation": 2, "tuning": 2},
        "minimum_viable": "Paddle + bola + 1 fileira tijolos + placar. 10 min",
        "common_bugs": ["Bola atravessa paddle", "Loop horizontal", "Power-up cai para sempre"],
        "godot_subsystems": ["CharacterBody2D", "StaticBody2D", "Area2D", "CanvasLayer"],
        "references": ["Breakout", "Arkanoid", "DX-Ball"],
        "combines_with": [],
    },
    "metroidvania": {
        "description": "Metroidvania: plataforma + exploracao interconectada com habilidades desbloqueaveis",
        "quickstart_phrase_pt": "jogo de exploracao com plataforma, desbloqueie habilidades para acessar novas areas do mapa",
        "camera": "side-scroll 2D", "root_node": "Node2D",
        "essential_nodes": ["CharacterBody2D (habilidades)", "Room (Node2D)", "Door (Area2D)", "Ability Gate (StaticBody2D)", "Map (Control)", "SavePoint (Area2D)", "BossDoor"],
        "core_mechanics": ["Movimento plataforma + dash/double jump/wall jump", "Habilidade-gate", "Backtracking", "Mapa revelado", "Chefoes guardam habilidades", "Upgrades encontrados no mapa"],
        "inputs": ["move/jump/attack", "dash (Shift)", "map (Tab)", "inventory (I)"],
        "typical_scripts": ["player.gd", "room_transition.gd", "door.gd", "ability_manager.gd", "map_screen.gd", "boss.gd"],
        "difficulty": {"design": 5, "implementation": 5, "tuning": 4},
        "minimum_viable": "3 salas + 1 porta trancada + 1 power-up",
        "common_bugs": ["Transicao posicao errada", "Mapa desatualizado", "Gate bypassado"],
        "godot_subsystems": ["CharacterBody2D", "Camera2D", "TileMapLayer", "Area2D", "Control"],
        "references": ["Hollow Knight", "Super Metroid", "Castlevania: SOTN", "Ori"],
        "combines_with": ["platformer"],
    },
    "racing_top_down": {
        "description": "Corrida top-down: aceleracao, frenagem, drift. Voltas em pista",
        "quickstart_phrase_pt": "jogo de corrida visto de cima, acelere, freie e derrape para vencer voltas na pista",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["Car (CharacterBody2D)", "Track (TileMapLayer + Path2D)", "Checkpoint (Area2D)", "AI Car", "HUD (posicao/volta/tempo)"],
        "core_mechanics": ["Fisica arcade com drift", "Pista fechada com checkpoints", "AI segue Path2D", "Power-ups na pista", "Vencedor: primeiro a completar N voltas"],
        "inputs": ["accelerate (W)", "brake (S)", "steer_left (A)", "steer_right (D)"],
        "typical_scripts": ["car_physics.gd", "checkpoint_manager.gd", "ai_car.gd", "race_manager.gd", "hud.gd"],
        "difficulty": {"design": 2, "implementation": 3, "tuning": 4},
        "minimum_viable": "1 carro + pista oval + 2 checkpoints + voltas",
        "common_bugs": ["Atravessa parede", "Checkpoint nao registra", "AI preso em curva"],
        "godot_subsystems": ["CharacterBody2D", "Path2D", "Area2D", "Camera2D", "TileMapLayer"],
        "references": ["Micro Machines", "Reckless Getaway", "Death Rally"],
        "combines_with": [],
    },
    "visual_novel": {
        "description": "Visual novel: historia ramificada, dialogos, escolhas que afetam o final",
        "quickstart_phrase_pt": "jogo de historia interativa com dialogos, suas escolhas mudam o final da narrativa",
        "camera": "fixa", "root_node": "Control (CanvasLayer)",
        "essential_nodes": ["Background (TextureRect)", "CharacterSprite (TextureRect)", "DialogBox (Panel + RichTextLabel com typewriter)", "ChoiceButtons (VBoxContainer)", "SaveLoadScreen", "HistoryLog"],
        "core_mechanics": ["Dialogo com typewriter effect", "Escolhas ramificam historia", "Flags definem finais", "Multiplos finais", "Save/Load com screenshot", "Galeria desbloqueavel"],
        "inputs": ["confirm (Mouse Left/Enter)", "hide_ui (H)"],
        "typical_scripts": ["dialog_manager.gd", "script_loader.gd", "choice_handler.gd", "save_system.gd", "flag_manager.gd"],
        "difficulty": {"design": 4, "implementation": 2, "tuning": 1},
        "minimum_viable": "1 cena + 1 personagem + typewriter + 1 escolha",
        "common_bugs": ["Texto avanca rapido", "Flag nao registra", "Save carrega cena errada"],
        "godot_subsystems": ["Control", "RichTextLabel", "TextureRect", "FileAccess", "JSON"],
        "references": ["Doki Doki Literature Club", "Ace Attorney", "VA-11 Hall-A"],
        "combines_with": ["rpg_turn_based"],
    },
    "idle_clicker": {
        "description": "Idle/clicker: clique para ganhar recurso, upgrades, automacao. Numeros exponenciais",
        "quickstart_phrase_pt": "jogo de clique incremental, clique para ganhar recursos, compre upgrades e automatize",
        "camera": "fixa", "root_node": "Control",
        "essential_nodes": ["ClickArea (TextureButton)", "ResourceDisplay (Label com 1.2K/3.4M)", "UpgradeShop (VBoxContainer)", "AutoGenerator (Timer)", "PrestigeButton"],
        "core_mechanics": ["Clique = +1 recurso", "Upgrades: +clique, +auto, +multiplicador", "Custo exponencial (1.15x)", "Automacao por Timer", "Notacao compacta", "Prestige: reset com bonus permanente"],
        "inputs": ["mouse_click"],
        "typical_scripts": ["game_manager.gd", "upgrade_shop.gd", "click_handler.gd", "auto_generator.gd", "prestige.gd"],
        "difficulty": {"design": 3, "implementation": 2, "tuning": 4},
        "minimum_viable": "Botao + contador + 3 upgrades",
        "common_bugs": ["Overflow negativo", "Custo nao escala", "Auto-generator pos-prestige"],
        "godot_subsystems": ["Control", "Timer", "Tween", "Curve"],
        "references": ["Cookie Clicker", "Adventure Capitalist"],
        "combines_with": [],
    },
    "physics_puzzle": {
        "description": "Physics puzzle: usar gravidade, colisao e joints para resolver puzzles",
        "quickstart_phrase_pt": "jogo de puzzle com fisica realista, use a gravidade e colisoes para resolver desafios",
        "camera": "side-scroll 2D", "root_node": "Node2D",
        "essential_nodes": ["PhysicsObjects (RigidBody2D)", "Launcher (mirar+lancar)", "Target (Area2D)", "Joint2D", "ResetButton", "HUD (nivel/estrelas)"],
        "core_mechanics": ["Fisica real: gravidade, atrito, elasticidade", "Interacao: drag, slingshot, corte", "Solucao baseada em fisica", "1-3 estrelas por nivel"],
        "inputs": ["mouse_drag", "touch"],
        "typical_scripts": ["launcher.gd", "physics_object.gd", "target.gd", "level_manager.gd", "hud.gd"],
        "difficulty": {"design": 4, "implementation": 3, "tuning": 4},
        "minimum_viable": "1 objeto + 1 lancador + 1 alvo",
        "common_bugs": ["Objeto sem gravidade", "Joint quebra sozinho", "Drag falha mobile"],
        "godot_subsystems": ["RigidBody2D", "Joint2D", "Area2D", "PhysicsMaterial"],
        "references": ["Angry Birds", "Cut the Rope", "World of Goo"],
        "combines_with": [],
    },
    "twin_stick_shooter": {
        "description": "Twin-stick: WASD move, setas atiram 8 dir. Arena survival com waves",
        "quickstart_phrase_pt": "jogo de arena com dois controles, mova com um e atire com o outro contra waves de inimigos",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["CharacterBody2D (WASD+setas)", "Bullet (Area2D 8 dir)", "Enemy (spawna bordas)", "Spawner (Timer)", "PowerUp (Area2D)", "HUD (score/wave/HP)"],
        "core_mechanics": ["Left=movimento, Right=tiro (8 dir)", "Inimigos convergem no jogador", "Waves progressivas", "Power-ups: spread, bomb, speed"],
        "inputs": ["move (WASD)", "shoot (Setas)", "bomb (Espaco)"],
        "typical_scripts": ["player.gd", "bullet.gd", "enemy.gd", "spawner.gd", "powerup.gd", "hud.gd"],
        "difficulty": {"design": 2, "implementation": 2, "tuning": 3},
        "minimum_viable": "Move + atira 4 dir + inimigos + score",
        "common_bugs": ["Tiro direcao errada", "Inimigo spawna fora", "Wave nao avanca"],
        "godot_subsystems": ["CharacterBody2D", "Timer", "Area2D", "Input dual mapping"],
        "references": ["Geometry Wars", "Smash TV", "Nuclear Throne"],
        "combines_with": ["bullet_hell"],
    },
    "snake_classic": {
        "description": "Snake: cobra cresce ao comer, morre ao colidir. Movimento em grid",
        "quickstart_phrase_pt": "jogo da cobrinha, controle a cobra no grid, coma a comida para crescer e nao bata nas paredes",
        "camera": "top-down 2D fixa", "root_node": "Node2D",
        "essential_nodes": ["Grid (Node2D)", "SnakeHead (ColorRect)", "SnakeBody (Array)", "Food (Sprite2D)", "Wall (StaticBody2D)", "HUD (score/high score)"],
        "core_mechanics": ["Movimento em grid com tick", "Setas mudam direcao", "Comer food = +1 segmento +10 score", "Morte: parede ou proprio corpo", "Velocidade aumenta"],
        "inputs": ["move_up/down/left/right (Setas)"],
        "typical_scripts": ["snake.gd", "food_spawner.gd", "grid.gd", "hud.gd"],
        "difficulty": {"design": 1, "implementation": 1, "tuning": 1},
        "minimum_viable": "Cobra 3 segmentos + 1 food + game over parede",
        "common_bugs": ["Inverte direcao", "Food sobre corpo", "Corpo nao segue cabeca"],
        "godot_subsystems": ["Timer", "Array", "ColorRect", "Area2D"],
        "references": ["Snake (Nokia)", "Slither.io"],
        "combines_with": [],
    },
    "bullet_hell": {
        "description": "Bullet hell: dezenas de projeteis, hitbox 2px, foco em ESQUIVA",
        "quickstart_phrase_pt": "jogo de esquiva com dezenas de projeteis na tela, desvie dos padroes e derrote chefes dificeis",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["CharacterBody2D (hitbox 2px)", "Bullet (Area2D, patterns)", "Boss (multi-phase)", "HUD (vidas/bombs/score)"],
        "core_mechanics": ["Hitbox 2px no centro", "Focus: Shift = lento + hitbox visivel", "Object pooling para balas", "Boss phases a cada 25% HP"],
        "inputs": ["move_4dir", "focus (Shift)", "bomb (X)"],
        "typical_scripts": ["player.gd", "bullet_pool.gd", "boss.gd", "pattern_factory.gd", "hud.gd"],
        "difficulty": {"design": 4, "implementation": 4, "tuning": 5},
        "minimum_viable": "Move + hitbox 2px + 1 pattern + boss 1 fase",
        "common_bugs": ["Hitbox nao corresponde", "Pool esgota", "Boss nao transiciona"],
        "godot_subsystems": ["CharacterBody2D", "Area2D", "Object Pool (Array)", "Timer"],
        "references": ["Touhou", "Jamestown", "Ikaruga"],
        "combines_with": ["top_down_shooter"],
    },
    "flappy_bird": {
        "description": "Flappy Bird: passaro voa entre canos, 1 toque = 1 pulo. Obstaculos em scroll lateral",
        "quickstart_phrase_pt": "jogo do passarinho que voa entre canos, toque na tela para pular e nao bata nos obstaculos",
        "camera": "side-scroll 2D", "root_node": "Node2D",
        "essential_nodes": ["Bird (CharacterBody2D)", "PipePair (StaticBody2D)", "Spawner (Timer)", "Ground (StaticBody2D)", "HUD (score/high score)"],
        "core_mechanics": ["Gravidade constante", "1 toque = impulso para cima", "Canos spawnam em pares com gap aleatorio", "Scroll horizontal continuo", "Game over ao colidir com cano ou chao", "Score conta canos passados"],
        "inputs": ["flap (Espaco/Click/Touch)"],
        "typical_scripts": ["bird.gd", "pipe_spawner.gd", "pipe.gd", "ground_scroll.gd", "hud.gd"],
        "difficulty": {"design": 1, "implementation": 1, "tuning": 1},
        "minimum_viable": "Passaro + gravidade + pulo + 1 par de canos + game over colisao",
        "common_bugs": ["Hitbox maior que sprite", "Cano spawna fora da tela", "Score conta multiplas vezes"],
        "godot_subsystems": ["CharacterBody2D", "StaticBody2D", "Timer", "Area2D"],
        "references": ["Flappy Bird", "Flappy Dunk"],
        "combines_with": [],
    },
    "pong": {
        "description": "Pong: dois paddles, uma bola, rebate para marcar ponto. Jogo de reflexo classico",
        "quickstart_phrase_pt": "jogo de ping-pong com dois paddles e uma bola, rebata para marcar ponto no adversario",
        "camera": "top-down 2D fixa", "root_node": "Node2D",
        "essential_nodes": ["PaddleLeft (CharacterBody2D)", "PaddleRight (CharacterBody2D ou AI)", "Ball (CharacterBody2D)", "Wall (StaticBody2D)", "HUD (score P1/P2)"],
        "core_mechanics": ["Paddles movem verticalmente", "Bola quica nas paredes e paddles", "Angulo de rebatida varia com posicao do paddle", "Ponto quando bola passa do paddle", "Vence quem fizer N pontos primeiro", "AI basica: paddle segue Y da bola"],
        "inputs": ["move_up/down P1 (W/S)", "move_up/down P2 (Setas)"],
        "typical_scripts": ["paddle.gd", "ball.gd", "ai_paddle.gd", "wall.gd", "hud.gd"],
        "difficulty": {"design": 1, "implementation": 1, "tuning": 1},
        "minimum_viable": "2 paddles + bola + paredes + placar",
        "common_bugs": ["Bola atravessa paddle", "Bola prende na parede", "AI imbatível ou muito facil"],
        "godot_subsystems": ["CharacterBody2D", "StaticBody2D", "Area2D", "CanvasLayer"],
        "references": ["Pong (Atari)", "Pong Quest"],
        "combines_with": [],
    },
    "space_invaders": {
        "description": "Space Invaders: nave na base atira em aliens que descem em formacao. Clássico dos arcades",
        "quickstart_phrase_pt": "jogo de nave que atira em aliens, eles descem em formacao e voce precisa eliminar todos antes que cheguem",
        "camera": "top-down 2D fixa", "root_node": "Node2D",
        "essential_nodes": ["Player (CharacterBody2D move horizontal)", "Bullet (Area2D)", "Alien (Area2D em grid)", "Barrier (StaticBody2D)", "HUD (score/vidas)"],
        "core_mechanics": ["Nave move horizontalmente na base", "Atira 1 tiro por vez (cooldown)", "Aliens em grid movem lateralmente + descem", "Barreiras protegem mas degradam", "Velocidade dos aliens aumenta ao eliminar", "Game over se aliens chegarem na base ou nave morta"],
        "inputs": ["move_left/right (A/D ou Setas)", "shoot (Espaco)"],
        "typical_scripts": ["player.gd", "bullet.gd", "alien.gd", "alien_grid.gd", "barrier.gd", "hud.gd"],
        "difficulty": {"design": 1, "implementation": 2, "tuning": 2},
        "minimum_viable": "Nave + atira + 10 aliens em grid + game over",
        "common_bugs": ["Aliens saem da tela", "Tiro destroi mais de 1 alien", "Barreira nao degrada"],
        "godot_subsystems": ["CharacterBody2D", "StaticBody2D", "Area2D", "Timer", "CanvasLayer"],
        "references": ["Space Invaders", "Galaga", "Galaxian"],
        "combines_with": ["tower_defense"],
    },
    "endless_runner": {
        "description": "Endless runner: personagem corre automaticamente, pula/desvia de obstaculos. Velocidade aumenta",
        "quickstart_phrase_pt": "jogo de corrida infinita, pule e desvie dos obstaculos enquanto a velocidade aumenta cada vez mais",
        "camera": "side-scroll 2D", "root_node": "Node2D",
        "essential_nodes": ["Runner (CharacterBody2D — so pula/desliza)", "Ground (scrolling infinito)", "ObstacleSpawner (Timer)", "Obstacle (StaticBody2D)", "HUD (score/distancia)"],
        "core_mechanics": ["Personagem corre automaticamente", "Pulo e/ou slide para desviar", "Obstaculos spawnam com gap aleatorio", "Velocidade aumenta com distancia", "Game over ao colidir", "Score = distancia percorrida"],
        "inputs": ["jump (Espaco/Seta Cima)", "slide (Seta Baixo)"],
        "typical_scripts": ["runner.gd", "ground_scroll.gd", "obstacle_spawner.gd", "obstacle.gd", "hud.gd"],
        "difficulty": {"design": 1, "implementation": 2, "tuning": 2},
        "minimum_viable": "Corredor + pulo + 2 tipos de obstaculo + terreno scroll + game over",
        "common_bugs": ["Obstaculo spawna sobreposto", "Terreno visivelmente emenda", "Hitbox muito generosa"],
        "godot_subsystems": ["CharacterBody2D", "StaticBody2D", "Timer", "Parallax2D", "CanvasLayer"],
        "references": ["Temple Run", "Subway Surfers", "Jetpack Joyride", "Canabalt"],
        "combines_with": ["platformer"],
    },
    "tetris_like": {
        "description": "Tetris: pecas caem, encaixe linhas completas para elimina-las. Grid 10x20 classico",
        "quickstart_phrase_pt": "jogo de encaixar pecas que caem, complete linhas horizontais para elimina-las e fazer pontos",
        "camera": "top-down 2D fixa", "root_node": "Node2D",
        "essential_nodes": ["Grid (Node2D 10x20)", "Piece (ColorRect array 4 blocos)", "Spawner (Timer + proxima peca)", "HUD (score/linhas/nivel)"],
        "core_mechanics": ["Grid 10x20 com celulas", "7 pecas padrao (I,O,T,S,Z,J,L)", "Peca cai com tick (Timer)", "Move/rotaciona com input", "Linha completa = elimina + score", "Nivel aumenta velocidade", "Game over se peca travar acima do topo"],
        "inputs": ["move_left/right (A/D)", "rotate (W/Seta Cima)", "soft_drop (S)", "hard_drop (Espaco)"],
        "typical_scripts": ["grid.gd", "piece.gd", "spawner.gd", "input_handler.gd", "hud.gd"],
        "difficulty": {"design": 2, "implementation": 3, "tuning": 2},
        "minimum_viable": "Grid 10x20 + 1 peca caindo + move/rotaciona + linha completa remove",
        "common_bugs": ["Rotacao na borda", "Peca atravessa bloco existente", "Linha parcialmente removida"],
        "godot_subsystems": ["ColorRect", "Timer", "Array 2D", "CanvasLayer"],
        "references": ["Tetris", "Tetris 99", "Puyo Puyo Tetris"],
        "combines_with": [],
    },
    "sokoban": {
        "description": "Sokoban: empurre caixas para posicoes marcadas no grid. Puzzle classico de logica",
        "quickstart_phrase_pt": "jogo de empurrar caixas, coloque cada caixa no lugar marcado usando o menor numero de movimentos",
        "camera": "top-down 2D fixa", "root_node": "Node2D",
        "essential_nodes": ["Grid (Node2D)", "Player (CharacterBody2D mov grid)", "Box (StaticBody2D)", "Target (Sprite2D)", "Wall (StaticBody2D)", "HUD (moves/level)"],
        "core_mechanics": ["Movimento em grid (cima/baixo/esq/dir)", "Jogador empurra 1 caixa por vez", "Caixa so move se espaco livre atras", "Todas as caixas nos alvos = venceu", "Undo (desfazer movimento)", "Multiplos niveis com dificuldade crescente"],
        "inputs": ["move_up/down/left/right (Setas/WASD)", "undo (Z)", "reset (R)"],
        "typical_scripts": ["grid.gd", "player.gd", "box.gd", "level_loader.gd", "hud.gd"],
        "difficulty": {"design": 3, "implementation": 2, "tuning": 1},
        "minimum_viable": "Grid + 1 jogador + 1 caixa + 1 alvo + empurra",
        "common_bugs": ["Caixa empurrada para fora do grid", "Undo quebrado apos reset", "Alvo nao detecta caixa sobreposta"],
        "godot_subsystems": ["CharacterBody2D", "StaticBody2D", "Sprite2D", "TileMapLayer", "CanvasLayer"],
        "references": ["Sokoban", "Baba Is You", "Stephen's Sausage Roll"],
        "combines_with": ["puzzle_match3"],
    },
    "beat_em_up": {
        "description": "Beat 'em up: lute contra ondas de inimigos, ande para a direita, avance fases. Cooperativo local",
        "quickstart_phrase_pt": "jogo de luta de rua, avance pelas fases derrotando ondas de inimigos com socos e chutes",
        "camera": "side-scroll 2D", "root_node": "Node2D",
        "essential_nodes": ["Player (CharacterBody2D + AnimatedSprite2D)", "Enemy (CharacterBody2D + AI)", "Arena (Area2D scroll-lock)", "HUD (HP/score/vidas)"],
        "core_mechanics": ["Movimento lateral + profundidade (eixo Y)", "Ataque: soco, chute, especial, agarrar", "Inimigos por wave na arena travada", "Scroll libera ao derrotar todos", "Itens de vida dropam", "Chefao a cada 3 arenas"],
        "inputs": ["move (WASD)", "attack (J)", "special (K)", "jump (Espaco)"],
        "typical_scripts": ["player.gd", "enemy.gd", "arena_manager.gd", "boss.gd", "item_drop.gd", "hud.gd"],
        "difficulty": {"design": 3, "implementation": 4, "tuning": 4},
        "minimum_viable": "Jogador + soco + 3 inimigos + arena travada + derrotar todos libera scroll",
        "common_bugs": ["Hitbox de ataque desalinhada", "Inimigo anda para fora da arena", "Scroll trava permanentemente"],
        "godot_subsystems": ["CharacterBody2D", "AnimationPlayer", "Area2D", "Camera2D", "CanvasLayer"],
        "references": ["Streets of Rage", "Final Fight", "Double Dragon", "Castle Crashers"],
        "combines_with": ["platformer"],
    },
    "stealth_2d": {
        "description": "Stealth 2D: evite ser detectado, esconda-se nas sombras, distraia guardas com objetos",
        "quickstart_phrase_pt": "jogo de furtividade, evite os guardas, esconda-se nas sombras e use distracoes para passar despercebido",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["Player (CharacterBody2D)", "Guard (CharacterBody2D + visao cone)", "Shadow (Area2D — esconderijo)", "NoiseMaker (distracao)", "Camera (Camera2D)", "HUD (alerta/deteccao)"],
        "core_mechanics": ["Cone de visao dos guardas (RayCast2D ou Area2D)", "Medidor de deteccao (0→100)", "Esconderijo em sombras/objetos", "Distrair guardas com objetos/sons", "Rotas de patrulha dos guardas", "Game over se detectado completamente"],
        "inputs": ["move (WASD)", "interact/hide (E)", "throw_distraction (Q)"],
        "typical_scripts": ["player.gd", "guard.gd", "vision_cone.gd", "detection_meter.gd", "distraction.gd", "hud.gd"],
        "difficulty": {"design": 4, "implementation": 4, "tuning": 3},
        "minimum_viable": "Jogador + 1 guarda com cone de visao + 1 esconderijo + deteccao",
        "common_bugs": ["Cone de visao atravessa paredes", "Guarda nao detecta som", "Esconderijo nao reseta deteccao"],
        "godot_subsystems": ["CharacterBody2D", "RayCast2D", "Area2D", "NavigationAgent2D", "CanvasLayer"],
        "references": ["Metal Gear", "Mark of the Ninja", "Gunpoint", "Invisible Inc."],
        "combines_with": ["platformer", "metroidvania"],
    },
    "asteroids": {
        "description": "Asteroids: nave gira 360°, atira em asteroides que se partem. Fisica com inercia e wrap-around",
        "quickstart_phrase_pt": "jogo de nave no espaco, gire e atire em asteroides que se quebram em pedacos menores",
        "camera": "top-down 2D", "root_node": "Node2D",
        "essential_nodes": ["Ship (CharacterBody2D com rotacao)", "Bullet (Area2D)", "Asteroid (RigidBody2D — grande/medio/pequeno)", "Spawner (Timer)", "HUD (score/vidas)"],
        "core_mechanics": ["Nave com rotacao 360° e inercia", "Tiro na direcao do nariz da nave", "Asteroides grandes se partem em 2 medios", "Medios se partem em 2 pequenos", "Pequenos somem ao serem atingidos", "Wrap-around: sair da tela = entrar do outro lado", "Game over se colidir com asteroide"],
        "inputs": ["rotate_left/right (A/D ou Setas)", "thrust (W/Seta Cima)", "shoot (Espaco)"],
        "typical_scripts": ["ship.gd", "bullet.gd", "asteroid.gd", "spawner.gd", "hud.gd"],
        "difficulty": {"design": 2, "implementation": 2, "tuning": 1},
        "minimum_viable": "Nave + rotacao + tiro + 1 asteroide grande que se parte",
        "common_bugs": ["Inercia infinita", "Wrap-around nao funciona nas bordas", "Asteroide parte mas pedacos nao tem velocity"],
        "godot_subsystems": ["CharacterBody2D", "RigidBody2D", "Area2D", "Timer", "CanvasLayer"],
        "references": ["Asteroids (Atari)", "Geometry Wars", "Subspace"],
        "combines_with": ["top_down_shooter"],
    },
    "bubble_shooter": {
        "description": "Bubble Shooter: atire bolhas coloridas, forme grupos de 3+ da mesma cor para estourar",
        "quickstart_phrase_pt": "jogo de atirar bolhas coloridas, forme grupos de 3 ou mais da mesma cor para estourar",
        "camera": "top-down 2D fixa", "root_node": "Node2D",
        "essential_nodes": ["Grid (Node2D com bolhas em hexagono)", "Shooter (Marker2D + mira)", "Bubble (Sprite2D colorida)", "AimLine (Line2D)", "HUD (score/bolhas restantes)"],
        "core_mechanics": ["Grid hexagonal de bolhas no topo", "Atirador na base com mira (mouse)", "Atira bolha que gruda no grid ou em outra bolha", "3+ bolhas da mesma cor adjacentes = estouram", "Bolhas orfas (sem conexao ao topo) caem", "Nova fileira de bolhas desce periodicamente", "Game over se bolhas atingirem a base"],
        "inputs": ["aim (Mouse)", "shoot (Mouse Left)"],
        "typical_scripts": ["grid.gd", "bubble.gd", "shooter.gd", "aim_line.gd", "hud.gd"],
        "difficulty": {"design": 2, "implementation": 3, "tuning": 1},
        "minimum_viable": "Grid hexagonal + atirador + mira + bolhas grudam + match-3 estoura",
        "common_bugs": ["Bolha gruda em posicao errada no hexagono", "Orfas nao caem", "Mira nao alinha com grid"],
        "godot_subsystems": ["Sprite2D", "Line2D", "Area2D", "Marker2D", "CanvasLayer"],
        "references": ["Puzzle Bobble", "Bust-a-Move", "Bubble Witch Saga"],
        "combines_with": ["puzzle_match3"],
    },
    "pacman": {
        "description": "Pac-Man: navegue no labirinto, coma todos os pontos e fuja dos fantasmas. Power-ups viram o jogo",
        "quickstart_phrase_pt": "jogo de labirinto, colete todos os pontos e fuja dos fantasmas, coma a pilula para poder devora-los",
        "camera": "top-down 2D fixa", "root_node": "Node2D",
        "essential_nodes": ["Maze (TileMapLayer com paredes)", "PacMan (CharacterBody2D mov grid)", "Ghost x4 (CharacterBody2D + AI)", "Dot (Area2D)", "PowerPellet (Area2D)", "HUD (score/vidas)"],
        "core_mechanics": ["Labirinto fixo com paredes", "Movimento em grid (troca direcao nas interseccoes)", "Comer todos os dots = venceu nivel", "4 fantasmas com AI: perseguicao, dispersao, patrulha", "Power pellet: fantasmas ficam azuis e vulneraveis por 8s", "Comer fantasma azul = +200/400/800/1600 pontos", "Fruta bonus aparece 2x por nivel"],
        "inputs": ["move_up/down/left/right (Setas/WASD)"],
        "typical_scripts": ["pacman.gd", "ghost.gd", "ghost_ai.gd", "dot.gd", "power_pellet.gd", "maze.gd", "hud.gd"],
        "difficulty": {"design": 3, "implementation": 3, "tuning": 2},
        "minimum_viable": "Labirinto + PacMan + dots + 1 fantasma perseguidor + power pellet",
        "common_bugs": ["PacMan atravessa parede", "Fantasma preso em canto", "Power pellet nao reverte apos timer"],
        "godot_subsystems": ["CharacterBody2D", "TileMapLayer", "Area2D", "Timer", "CanvasLayer"],
        "references": ["Pac-Man", "Ms. Pac-Man", "Pac-Man Championship Edition"],
        "combines_with": [],
    },
    "doodle_jump": {
        "description": "Doodle Jump: pule de plataforma em plataforma subindo infinitamente. Plataformas quebram, tem molas e jetpack",
        "quickstart_phrase_pt": "jogo de pular de plataforma em plataforma subindo sem parar, use molas e jetpacks para ir mais alto",
        "camera": "side-scroll 2D vertical", "root_node": "Node2D",
        "essential_nodes": ["Jumper (CharacterBody2D — so gravidade+pulo)", "Platform (StaticBody2D — normal/quebravel/mola/movel)", "PlatformSpawner (Timer)", "Camera (Camera2D follow Y)", "HUD (score/altitude)"],
        "core_mechanics": ["Personagem pula automaticamente ao tocar plataforma", "Plataformas sobem infinitamente (scroll vertical)", "Tipos: normal, quebravel (some apos pisar), mola (impulso extra), movel (horizontal)", "Camera sobe com jogador", "Cair da tela = game over", "Power-ups: jetpack, foguete, elice"],
        "inputs": ["move_left/right (A/D ou Setas)", "shoot (Espaco — se power-up)"],
        "typical_scripts": ["jumper.gd", "platform.gd", "platform_spawner.gd", "camera.gd", "hud.gd"],
        "difficulty": {"design": 1, "implementation": 1, "tuning": 1},
        "minimum_viable": "Personagem + pulo + 3 plataformas + scroll vertical + game over ao cair",
        "common_bugs": ["Plataforma spawna muito longe", "Jogador atravessa plataforma subindo", "Camera nao acompanha"],
        "godot_subsystems": ["CharacterBody2D", "StaticBody2D", "Timer", "Camera2D", "CanvasLayer"],
        "references": ["Doodle Jump", "Mega Jump", "Papi Jump"],
        "combines_with": ["platformer"],
    },
    "minesweeper": {
        "description": "Campo Minado: revele celulas do grid, use os numeros para deduzir onde estao as minas sem explodir",
        "quickstart_phrase_pt": "jogo de campo minado, revele as celulas com cuidado e use os numeros para descobrir onde estao as minas",
        "camera": "top-down 2D fixa", "root_node": "Control",
        "essential_nodes": ["Grid (GridContainer de botoes)", "Cell (Button — revelado/bandeira/interrogacao/escondido)", "MineCounter (Label)", "Timer (Label)", "HUD (minas restantes/tempo)"],
        "core_mechanics": ["Grid NxM com M minas aleatorias", "Clique esquerdo: revela celula", "Numero = quantas minas nas 8 celulas vizinhas", "Celula com 0 minas vizinhas = flood-fill revela area", "Clique direito: bandeira → interrogação → nada", "Game over ao revelar mina", "Vence ao revelar todas as celulas sem mina"],
        "inputs": ["reveal (Mouse Left)", "flag (Mouse Right)"],
        "typical_scripts": ["grid.gd", "cell.gd", "game_manager.gd", "hud.gd"],
        "difficulty": {"design": 2, "implementation": 2, "tuning": 1},
        "minimum_viable": "Grid 9x9 + 10 minas + revela/bandeira + flood-fill + game over",
        "common_bugs": ["Flood-fill recursivo estoura stack", "Bandeira conta errada", "Primeira revelacao acerta mina"],
        "godot_subsystems": ["Control", "Button", "GridContainer", "Timer"],
        "references": ["Minesweeper (Microsoft)", "Minesweeper Online", "Tametsi"],
        "combines_with": [],
    },
    "frogger": {
        "description": "Frogger: atravesse a rua e o rio, desvie de carros e pule em troncos para chegar ao outro lado",
        "quickstart_phrase_pt": "jogo do sapo que atravessa a rua e o rio, desvie dos carros e pule nos troncos para chegar ao outro lado",
        "camera": "top-down 2D fixa", "root_node": "Node2D",
        "essential_nodes": ["Frog (CharacterBody2D mov grid)", "Car (CharacterBody2D scroll horizontal)", "Log (CharacterBody2D — tronco/tartaruga)", "LaneManager (Timer)", "Goal (Area2D)", "HUD (vidas/tempo)"],
        "core_mechanics": ["Sapo move em grid (cima/baixo/esq/dir)", "Multiplas lanes horizontais: rua (carros) e rio (troncos)", "Carros matam sapo ao colidir", "Troncos carregam sapo — sapo anda junto", "5 slots de chegada no topo", "Preencher todos os slots = venceu nivel", "Timer regressivo — game over se acabar o tempo"],
        "inputs": ["move_up/down/left/right (Setas/WASD)"],
        "typical_scripts": ["frog.gd", "car_spawner.gd", "log_spawner.gd", "lane.gd", "goal.gd", "hud.gd"],
        "difficulty": {"design": 2, "implementation": 2, "tuning": 2},
        "minimum_viable": "Sapo + 2 lanes de rua + 1 lane de rio + 1 slot de chegada + game over",
        "common_bugs": ["Sapo nao move com tronco", "Multiplos sapos no mesmo slot", "Carro atravessa sapo sem matar"],
        "godot_subsystems": ["CharacterBody2D", "Area2D", "Timer", "CanvasLayer"],
        "references": ["Frogger", "Crossy Road", "Frogger in Toy Town"],
        "combines_with": [],
    },
    "memory_match": {
        "description": "Jogo da Memoria: vire cartas e encontre os pares iguais no menor numero de tentativas",
        "quickstart_phrase_pt": "jogo da memoria, vire as cartas e encontre os pares iguais antes que o tempo acabe",
        "camera": "fixa", "root_node": "Control",
        "essential_nodes": ["Grid (GridContainer de botoes)", "Card (Button — frente/verso)", "CardManager (logica de pares)", "HUD (tentativas/tempo/pares)"],
        "core_mechanics": ["Grid de cartas viradas para baixo (N pares)", "Clique vira carta (animacao de flip)", "Duas cartas viradas: se iguais = permanecem, se diferentes = desviram", "Contador de tentativas", "Todas as cartas viradas = venceu", "Timer opcional para desafio"],
        "inputs": ["select_card (Mouse Left)"],
        "typical_scripts": ["card.gd", "card_manager.gd", "grid.gd", "hud.gd"],
        "difficulty": {"design": 1, "implementation": 1, "tuning": 1},
        "minimum_viable": "Grid 4x3 + 6 pares + flip + match detection + game over/win",
        "common_bugs": ["Flip animation corta", "Clicar mesma carta 2x conta como par", "Timer continua apos vitoria"],
        "godot_subsystems": ["Control", "Button", "GridContainer", "Timer", "Tween"],
        "references": ["Memory Match", "Concentration", "Pairs"],
        "combines_with": [],
    },
}


def get_game_patterns() -> list[dict]:
    return [{"name": n, "description": i["description"], "camera": i["camera"],
             "essential_count": len(i["essential_nodes"]), "mechanic_count": len(i["core_mechanics"])}
            for n, i in GAME_PATTERNS.items()]


def get_game_pattern(name: str) -> dict | None:
    return GAME_PATTERNS.get(name)
