"""domains/node/manifest.py"""
from registry.types import DomainManifest, OpSpec, Phase; from . import handlers
MANIFEST = DomainManifest(domain="node", tool_name="node_manage", title="Nós", namespace="project", version="1.0.0",
    description="Gerencia nós: adicionar, remover, propriedades, re-parentar, sinais.\nQUANDO USAR: para construir árvore de cena.\nQUANDO NÃO USAR: para criar cena (use scene_manage).",
    phases=[Phase.DESIGN, Phase.PROTOTIPO, Phase.CONTEUDO], annotations={"destructiveHint": True, "idempotentHint": False, "openWorldHint": True},
    ops=[OpSpec("create", handlers.add_node, "Adiciona nó", {"scene_path": {"type": "string", "required": True}, "parent_node_path": {"type": "string", "required": True}, "node_name": {"type": "string", "required": True}, "node_type": {"type": "string", "required": True}}, [{"scene_path": "scenes/game.tscn", "parent_node_path": ".", "node_name": "Player", "node_type": "CharacterBody2D"}]),
         OpSpec("delete", handlers.delete_node, "Remove nó", {"scene_path": {"type": "string", "required": True}, "node_path": {"type": "string", "required": True}}, [{"scene_path": "scenes/game.tscn", "node_path": "./OldNode"}]),
         OpSpec("set_property", handlers.set_node_property, "Define propriedade", {"scene_path": {"type": "string", "required": True}, "node_path": {"type": "string", "required": True}, "property_name": {"type": "string", "required": True}}, [{"scene_path": "scenes/game.tscn", "node_path": "./Player", "property_name": "speed", "value": 400}]),
         OpSpec("get_property", handlers.get_node_property, "Lê propriedade", {"scene_path": {"type": "string", "required": True}, "node_path": {"type": "string", "required": True}, "property_name": {"type": "string", "required": True}}, [{"scene_path": "scenes/game.tscn", "node_path": "./Player", "property_name": "position"}]),
         OpSpec("reparent", handlers.reparent_node, "Re-parenta nó", {"scene_path": {"type": "string", "required": True}, "node_path": {"type": "string", "required": True}, "new_parent_path": {"type": "string", "required": True}}, [{"scene_path": "scenes/game.tscn", "node_path": "./Enemy", "new_parent_path": "./Enemies"}]),
         OpSpec("connect_signal", handlers.connect_signal, "Conecta sinal", {"scene_path": {"type": "string", "required": True}, "source_node": {"type": "string", "required": True}, "signal_name": {"type": "string", "required": True}, "target_node": {"type": "string", "required": True}, "target_method": {"type": "string", "required": True}}, [{"scene_path": "scenes/game.tscn", "source_node": "./Button", "signal_name": "pressed", "target_node": "./Game", "target_method": "_on_button_pressed"}]),
         OpSpec("list_signals", handlers.list_signals_for_node, "Lista sinais", {"scene_path": {"type": "string", "required": True}, "node_path": {"type": "string", "required": True}}, [{"scene_path": "scenes/game.tscn", "node_path": "./Button"}])],
    tags=["nó", "godot", "cena"])
